# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Publish parallel-consumer-parent

on:
  pull_request:
    branches:
      - master
    types:
      - closed


jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout parallel-consumer-parent
        uses: actions/checkout@v2
      - name: Find the version from the project version
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Print env
        run: |
          echo Publishing ${RELEASE_VERSION}
      - name: Set up Eclipse Temurin JDK 17
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Create Package
        env:
          EDS_PUBLISH: ${{ secrets.EDS_PUBLISH }}
        run: mvn clean package -DskipTests --file pom.xml --settings settings.xml
      - name: Publish Package
        env:
          EDS_PUBLISH: ${{ secrets.EDS_PUBLISH }}
        run: |
          mvn -B deploy:deploy-file -Durl=https://edgenettfs.pkgs.visualstudio.com/DataPlatform/_packaging/dp.internal/maven/v1 -DrepositoryId=dp.internal -Dfile=target/rdp-parallel-consumer-${RELEASE_VERSION}.jar -DgroupId=com.riversand.dataplatform -DartifactId=rdp-parallel-consumer -Dversion=${RELEASE_VERSION} -Dpackaging=jar -DgeneratePom=true -DuniqueVersion=false --settings settings.xml
